---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sam
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sam
  template:
    metadata:
      labels:
        app: sam
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: samd
        image: quay.io/repository/brice/metrics-demo:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

